const regex = {
    IkariamGetClass: /ikariam\.getClass[(]ajax\.Responder,\s\[\[["]\w+["],[{]["]name["][:]\"(?<name>\w+)["],["]id["][:]["](?<id>\d+)["],["]phase["][:](?<phase>\d+),["]isCapital["][:](?<isCapital>\w+),["].*["]islandId["][:]["](?<islandId>\d+)["],["]islandName["][:]["](?<islandName>\w+)["],["]islandXCoord["][:]["](?<islandXCoord>\d+)["],["]islandYCoord["][:]["](?<islandYCoord>\d+)["].*,["]underConstruction["][:](?<underConstruction>[-]\d+|\d+),["]endUpgradeTime["][:](?<endUpgradeTime>[-]\d+|\d+),["]startUpgradeTime["][:](?<startUpgradeTime>[-]\d+|\d+),["]position["][:](?<position>\[.*\]),["](:?beachboys|registration)["]/,
    dataSetForView: /producedTradegood[:]\s["](?<producedTradegood>\d)["],\s+.*\s+currentResources[:]\sJSON\.parse[(]['](?<currentResources>.*)['][)],\s+.*\s+maxResources[:]\sJSON\.parse[(]['](?<maxResources>.*)['][)],\s+.*\s+branchOfficeResources[:]\sJSON\.parse[(]['](?<branchOfficeResources>.*)['][)],\s+.*\s+resourceProduction[:]\s(?<resourceProduction>(?:\d+|\.)*),\s+.*\s+tradegoodProduction[:]\s(?<tradegoodProduction>(?:\d+|\.)*),\s+.*\s+wineSpendings[:]\s(?<wineSpendings>(?:\d+|\.)*),\s+wineTickInterval[:]\s(?:\d+|\.),\s+upkeep[:]\s(?<upkeep>[-](?:\d+|\.)*),\s+income[:]\s(?<income>(?:\d+|\.)*),\s+badTaxAccountant[:]\s(?:\d+|\.),\s+scientistsUpkeep[:]\s(?<scientistsUpkeep>[-](?:\d+|\.)*),\s+(?:.*\s+){18}actionRequest[:]\s["](?<actionRequest>\w+)["],\s+(?:.*\s+){18}relatedCityData[:]\sJSON\.parse[(]['](?<relatedCityData>.*)['][)],/,
    Responder: /ikariam.getClass[(]ajax\.Responder\,\s(.*)[)][;]\s+[}][)][;]\s+\<\/script\>/,
    playerHighscoreG: /view[=]avatarProfile[&]avatarId[=](?<avatarId>\d+)["]\s+(?:onclick[=]["]ajaxHandlerCall[(]this\.href[)][;]return\sfalse[;]["][>]\s+)?(?:class\=\"(?<inactive>\w+)\"\s(?:onclick[=]["]ajaxHandlerCall[(]this\.href[)][;]return\sfalse[;]["][>]\s+))?(?:[<]i[>](?:\w+|\-|á|é|í|ó|ñ|Ñ|\s+)*[<]\/i[>])?\s{32}(?<username>.{1,15})\s{28}\<\/a\>(?:\s+\<img\ssrc\=\"skin\/layout\/icon\-(?<palm>palm)\.png\"\/\>\s+)?\s+\<\/td\>\s+\<td\sclass\=\"allytag\"\>\s+(?:\<a\sclass\=\"allyLink\"\sonclick\=\"ajaxHandlerCall\(this\.href\)\;\sreturn\sfalse\;\"\s+href\=\"\?view\=allyPage\&oldView\=highscore\&allyId\=(?<allyId>\d+)\"\>(?<allyName>.{1,5})\<\/a\>)?/g,
    playerHighscore: /view[=]avatarProfile[&]avatarId[=](?<avatarId>\d+)["]\s+(?:onclick[=]["]ajaxHandlerCall[(]this\.href[)][;]return\sfalse[;]["][>]\s+)?(?:class\=\"(?<inactive>\w+)\"\s(?:onclick[=]["]ajaxHandlerCall[(]this\.href[)][;]return\sfalse[;]["][>]\s+))?(?:[<]i[>](?:\w+|\-|á|é|í|ó|ñ|Ñ|\s+)*[<]\/i[>])?\s{32}(?<username>.{1,15})\s{28}\<\/a\>(?:\s+\<img\ssrc\=\"skin\/layout\/icon\-(?<palm>palm)\.png\"\/\>\s+)?\s+\<\/td\>\s+\<td\sclass\=\"allytag\"\>\s+(?:\<a\sclass\=\"allyLink\"\sonclick\=\"ajaxHandlerCall\(this\.href\)\;\sreturn\sfalse\;\"\s+href\=\"\?view\=allyPage\&oldView\=highscore\&allyId\=(?<allyId>\d+)\"\>(?<allyName>.{1,5})\<\/a\>)?/,
    allyHighscoreG: /href\=\"\?view\=allyPage\&allyId\=(?<allyId>\d+)\&oldView\=highscore\"\>\s{33}(?<allyName>.{1,15})\((?<allyTagName>.{1,5})\s{32}\)/g,
    allyHighscore: /href\=\"\?view\=allyPage\&allyId\=(?<allyId>\d+)\&oldView\=highscore\"\>\s{33}(?<allyName>.{1,15})\((?<allyTagName>.{1,5})\s{32}\)/
}

module.exports = regex;