const regex = {
    IkariamGetClass: /ikariam\.getClass[(]ajax\.Responder,\s\[\[["]\w+["],[{]["]name["][:]\"(?<name>\w+)["],["]id["][:]["](?<id>\d+)["],["]phase["][:](?<phase>\d+),["]isCapital["][:](?<isCapital>\w+),["].*["]islandId["][:]["](?<islandId>\d+)["],["]islandName["][:]["](?<islandName>\w+)["],["]islandXCoord["][:]["](?<islandXCoord>\d+)["],["]islandYCoord["][:]["](?<islandYCoord>\d+)["].*,["]underConstruction["][:](?<underConstruction>[-]\d+|\d+),["]endUpgradeTime["][:](?<endUpgradeTime>[-]\d+|\d+),["]startUpgradeTime["][:](?<startUpgradeTime>[-]\d+|\d+),["]position["][:](?<position>\[.*\]),["](:?beachboys|registration)["]/,
    dataSetForView: /producedTradegood[:]\s["](?<producedTradegood>\d)["],\s+.*\s+currentResources[:]\sJSON\.parse[(]['](?<currentResources>.*)['][)],\s+.*\s+maxResources[:]\sJSON\.parse[(]['](?<maxResources>.*)['][)],\s+.*\s+branchOfficeResources[:]\sJSON\.parse[(]['](?<branchOfficeResources>.*)['][)],\s+.*\s+resourceProduction[:]\s(?<resourceProduction>(?:\d+|\.)*),\s+.*\s+tradegoodProduction[:]\s(?<tradegoodProduction>(?:\d+|\.)*),\s+.*\s+wineSpendings[:]\s(?<wineSpendings>(?:\d+|\.)*),\s+wineTickInterval[:]\s(?:\d+|\.),\s+upkeep[:]\s(?<upkeep>[-](?:\d+|\.)*),\s+income[:]\s(?<income>(?:\d+|\.)*),\s+badTaxAccountant[:]\s(?:\d+|\.),\s+scientistsUpkeep[:]\s(?<scientistsUpkeep>[-](?:\d+|\.)*),\s+(?:.*\s+){18}actionRequest[:]\s["](?<actionRequest>\w+)["],\s+(?:.*\s+){18}relatedCityData[:]\sJSON\.parse[(]['](?<relatedCityData>.*)['][)],/,
    Responder: /ikariam.getClass[(]ajax\.Responder\,\s(.*)[)][;]\s+[}][)][;]\s+\<\/script\>/,
    playerHighscoreG: /view[=]avatarProfile[&]avatarId[=](?<avatarId>\d+)["]\s+(?:onclick[=]["]ajaxHandlerCall[(]this\.href[)][;]return\sfalse[;]["][>]\s+)?(?:class\=\"(?<inactive>\w+)\"\s(?:onclick[=]["]ajaxHandlerCall[(]this\.href[)][;]return\sfalse[;]["][>]\s+))?(?:[<]i[>](?:\w+|\-|á|ñ|Ñ|é|ó|í|Ĥ|ä|ö|ŏ|É|\_|ō|á|í|ï|\s+)*[<]\/i[>])?\s+(?<username>(?:\w+|\-|á|ñ|Ñ|é|ó|í|Ĥ|ä|ö|ŏ|É|\_|ō|\_|ō|á|í|ï|\s)*(?:\w|\-))\s+[<]\/a[>]\s+(?:\<img\ssrc[=]\"skin\/layout\/icon\-(?<palm>palm)\.png\"\/\>\s+)?<\/td\>\s+\<td\sclass\=\"allytag\"\>\s+(?:\<a\sclass\=\"allyLink\"\sonclick\=\"ajaxHandlerCall\(this\.href\)\;\sreturn\sfalse\;\"\s+href\=\"\?view\=allyPage\&oldView\=highscore\&allyId\=(?<allyId>\d+)\"\>(?<allyName>(?:\w+|\-|á|ñ|Ñ|é|ó|í|Ĥ|ä|ö|ŏ|É|\_|ō|á|í|ï|\-)*)\<\/a\>\s+)?\<\/td\>/g,
    playerHighscore: /view[=]avatarProfile[&]avatarId[=](?<avatarId>\d+)["]\s+(?:onclick[=]["]ajaxHandlerCall[(]this\.href[)][;]return\sfalse[;]["][>]\s+)?(?:class\=\"(?<inactive>\w+)\"\s(?:onclick[=]["]ajaxHandlerCall[(]this\.href[)][;]return\sfalse[;]["][>]\s+))?(?:[<]i[>](?:\w+|\-|á|ñ|Ñ|é|ó|í|Ĥ|ä|ö|ŏ|É|\_|ō|á|í|ï|\s+)*[<]\/i[>])?\s+(?<username>(?:\w+|\-|á|ñ|Ñ|é|ó|í|Ĥ|ä|ö|ŏ|É|\_|ō|á|í|ï|\s)*(?:\w|\-))\s+[<]\/a[>]\s+(?:\<img\ssrc[=]\"skin\/layout\/icon\-(?<palm>palm)\.png\"\/\>\s+)?<\/td\>\s+\<td\sclass\=\"allytag\"\>\s+(?:\<a\sclass\=\"allyLink\"\sonclick\=\"ajaxHandlerCall\(this\.href\)\;\sreturn\sfalse\;\"\s+href\=\"\?view\=allyPage\&oldView\=highscore\&allyId\=(?<allyId>\d+)\"\>(?<allyName>(?:\w+|\-|á|ñ|Ñ|é|ó|í|Ĥ|ä|ö|ŏ|É|\_|ō|á|í|ï|\-)*)\<\/a\>\s+)?\<\/td\>/,
    allyHighscoreG: /href\=\"\?view\=allyPage\&allyId\=(?<allyId>\d+)\&oldView\=highscore\"\>\s+(?<allyName>(?:\w+|\-|á|ñ|Ñ|é|ó|í|Ĥ|ä|ö|ŏ|É|\_|ō|á|í|ï|\s)*(?:\w|\-))\((?<allyTagName>(?:\w+|\-|á|ñ|Ñ|é|ó|í|Ĥ|ä|ö|ŏ|É|\_|ō|á|í|ï|\-)*)\s+\)/g,
    allyHighscore: /href\=\"\?view\=allyPage\&allyId\=(?<allyId>\d+)\&oldView\=highscore\"\>\s+(?<allyName>(?:\w+|\-|á|ñ|Ñ|é|ó|í|Ĥ|ä|ö|ŏ|É|\_|ō|á|í|ï|\s)*(?:\w|\-))\((?<allyTagName>(?:\w+|\-|á|ñ|Ñ|é|ó|í|Ĥ|ä|ö|ŏ|É|\_|ō|á|í|ï|\-)*)\s+\)/
}

module.exports = regex;